{% set name = "openstep-plist" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openstep_plist-{{ version }}.tar.gz
  sha256: 453a56cdf534c6f42d24934d2ed7f95bc77c3d1a8acbc1881a4aa061a7d601a2

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cython
  host:
    - pip
    - python
    - setuptools
    - cython
    - setuptools-scm
  run:
    - python

test:
  imports:
    - openstep_plist
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fonttools/openstep-plist
  summary: ASCII plist parser written in Cython
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
