{% set name = "openstep-plist" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/openstep_plist-{{ version }}.tar.gz
  sha256: daf386652ae086bce8b18784c59a8252523faca3b1ded876bbf393594d862b78

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cython
  host:
    - pip
    - python
    - setuptools
    - cython
    - setuptools-scm
  run:
    - python

test:
  imports:
    - openstep_plist
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fonttools/openstep-plist
  summary: ASCII plist parser written in Cython
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
