{% set name = "openstep-plist" %}
{% set version = "0.3.0.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/openstep_plist-{{ version }}.zip
  sha256: 18aff3d5eded9ebfbedfeba444a3c048324697bf8a39bb04361c0dd53bfeab0b

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
    - cython
  host:
    - pip
    - python
    - cython
    - setuptools-scm
  run:
    - python

test:
  imports:
    - openstep_plist
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fonttools/openstep-plist
  summary: ASCII plist parser written in Cython
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
